[package]
name = "demo"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
askama = "0.12.1"
askama_axum = "0.4.0"
axum = { workspace = true }
axum-core = "0.5.0"
tokio = { workspace = true }

libpasskey.workspace = true
